<?php

function oeaw_theme() {
  $theme['oeaw_detail_dt'] = [
    'variables' => ['result' => NULL, 'header' => NULL, 'childResult' => NULL, 'childHeader' => NULL],
    'template' => 'dtDetail',
  ];  
  
  $theme['oeaw_root_dt'] = [
    'variables' => ['result' => NULL, 'header' => NULL],
    'template' => 'dtRoot',
  ];
  
  $theme['oeaw_success'] = [
    'variables' => ['result' => NULL],
    'template' => 'success',
  ];
  
  $theme['oeaw_success_resource'] = [
    'variables' => ['result' => NULL],
    'template' => 'success_res',
  ];

  return $theme;
}