<?php

function oeaw_theme() {
  $theme['oeaw_detail_dt'] = [
    'variables' => ['result' => NULL, 'header' => NULL, 'childResult' => NULL, 'childHeader' => NULL, 
        'editResData' => NULL, 'userid' => NULL, 'hasBinary' => NULL, 'jsonGraph' => NULL, 'hasImage' => NULL,],
    'template' => 'dtDetail',
  ];  
  
  $theme['oeaw_root_dt'] = [
    'variables' => ['result' => NULL, 'header' => NULL, 'userid' => NULL],
    'template' => 'dtRoot',
  ];
  
  $theme['oeaw_success'] = [
    'variables' => ['result' => NULL, 'userid' => NULL],
    'template' => 'success',
  ];
  
  $theme['oeaw_success_resource'] = [
    'variables' => ['result' => NULL, 'userid' => NULL],
    'template' => 'success_res',
  ];
  
  $theme['oeaw_search_res_dt'] = [
    'variables' => ['result' => NULL, 'searchedValues' => NULL, 'userid' => NULL],
    'template' => 'search_res',
  ];
  
  $theme['oeaw_search_class_res_dt'] = [
    'variables' => ['result' => NULL, 'searchedValues' => NULL, 'userid' => NULL],
    'template' => 'search_class_res',
  ];

  return $theme;
}


/*
 * Create a hook for the admin form page to we can use an external javascript file
 * 
 */
function oeaw_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){

    $form['#attached']['library'][] = 'oeaw/admin_forms_js';
    $form['#attached']['drupalSettings']['oeaw']['admin_forms_js']['variable'] = 'value';

    return $form;

}


